### PR TITLE
Added first sounds files

### PR DESCRIPTION
**Pull request by richelbilderbeek**
I've added the starting sound/tune in multiple formats (wav/mp3/ogg) for [this Issue](https://github.com/djog/djog_unos_2020/issues/63) in folder `assets/sound`. Also, I added an Audacity project, so I can extract the tank shooting and driving sounds as well.

I assume these sounds formats can be played in Processing. If not, I will happily convert these.

### CODE REVIEW

**Review by robkruger — CHANGES_REQUESTED** [review]
Both .wav and .mp3 are supported, so the .ogg can be removed. Processing recommends .wav, so in my opinion the .mp3 can also be removed, but maybe @rijkvp disagrees?

**Comment by richelbilderbeek** [comment]
Great, I will remove all except the WAV: thanks to git -whatever happens- we can always go back :+1:

**Comment by richelbilderbeek** [comment]
@robkruger I just updated the PR :+1:

**Comment by richelbilderbeek** [comment]
Added all the sound files :+1:

**Review by rijkvp — APPROVED** [review]
Nice! I agree

**Comment by rijkvp** [comment]
Btw you added the sounds in the `assets/sound` folder but the existing sounds were in the `assets/audio` folder:
image

**Comment by richelbilderbeek** [comment]
Silly me, I will rename the folder :rocket:

**Comment by richelbilderbeek** [comment]
@rijkvp done :+1:

**Review by rijkvp — APPROVED** [review]

**Pull request merged**
